### ISSUE TITLE
Copyright headers comment format incompatible with LOVE?

### ISSUE THREAD

**Issue by 1lostninja** [Zakru/opencrypt#5]
When running "love ." in the root of this repo:

Error

Syntax error: main.lua:16: unexpected symbol near '[[Copyright 2019 Zakru

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
]]'

Traceback

[C]: at 0x7ffa1ca328f0
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by 1lostninja** [comment]
Works fine with https://github.com/Zakru/opencrypt/archive/bc4c087b45d4a85412568fc2a995409449425099.zip

Hey... no monsters yet. No items either... 🥇 Who will accept the challenge?

**Comment by Zakru** [comment]
Hi, I've honestly kind of ditched this version of the project in favor of a Java version. I've also been really busy with military so that hasn't been progressing too quickly either. PRs will be accepted here though, if any come.

There is a prototype monster in the files, the world generator just doesn't use it.

**Comment by Zakru** [comment]
Resolved by #6
